# Generated by Django 4.1.5 on 2023-01-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_users_employee_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Techs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee_tech_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.IntegerField(choices=[(1, 'Wants To Learn'), (2, 'Can Work With'), (3, 'Proficient')])),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.techs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.users')),
            ],
        ),
    ]
