# Generated by Django 4.1.5 on 2023-01-27 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_techs_employee_tech_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee_tech_skills',
            options={'ordering': ['skill_level']},
        ),
        migrations.AlterModelOptions(
            name='techs',
            options={'ordering': ['tech_name']},
        ),
        migrations.AlterField(
            model_name='employee_tech_skills',
            name='skill_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee_tech_skills',
            name='tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech', to='backend.techs'),
        ),
        migrations.AlterField(
            model_name='employee_tech_skills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='backend.users'),
        ),
    ]
