# Generated by Django 4.1.5 on 2023-01-27 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_employee_tech_skills_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee_tech_skills',
            options={'ordering': ['tech_name']},
        ),
        migrations.RemoveField(
            model_name='employee_tech_skills',
            name='tech',
        ),
        migrations.AddField(
            model_name='employee_tech_skills',
            name='tech_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_tech_skills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_skills', to='backend.users'),
        ),
        migrations.DeleteModel(
            name='Techs',
        ),
    ]
