# Generated by Django 4.1.5 on 2023-01-28 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_employee_tech_skills_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Techs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_name', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='employee_tech_skills',
            options={'ordering': ['tech']},
        ),
        migrations.RemoveField(
            model_name='employee_tech_skills',
            name='tech_name',
        ),
        migrations.AlterField(
            model_name='employee_tech_skills',
            name='skill_level',
            field=models.IntegerField(choices=[(1, 'Wants To Learn'), (2, 'Can Work With'), (3, 'Proficient')]),
        ),
        migrations.AlterField(
            model_name='employee_tech_skills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='backend.users'),
        ),
        migrations.DeleteModel(
            name='Employee_projects',
        ),
        migrations.AddField(
            model_name='employee_tech_skills',
            name='tech',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tech', to='backend.techs'),
            preserve_default=False,
        ),
    ]
