version: '3'
services:
  frontend_staging:
    build:
      context: frontend/
      dockerfile: Dockerfile
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default
      - deployment
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 1s
      retries: 5

networks:
  deployment:
    name: deployment
    external: true
