version: '3.8'
services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - 443:443
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
      - /certs:/etc/nginx/certs
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 1s
      retries: 5
