# Generated by Django 4.1.5 on 2023-02-28 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_tech_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.IntegerField(choices=[(1, 'Wants To Learn'), (2, 'Can Work With'), (3, 'Proficient')])),
                ('tech_preference', models.BooleanField(null=True)),
            ],
            options={
                'ordering': ['tech'],
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('phone_number', models.TextField(null=True)),
                ('location_country', models.TextField(null=True)),
                ('location_city', models.TextField(null=True)),
                ('worktime_allocation', models.IntegerField(null=True)),
                ('allocation_until', models.DateField(null=True)),
                ('wants_to_do', models.TextField(null=True)),
                ('wants_not_to_do', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Techs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_name', models.TextField(unique=True)),
                ('employee', models.ManyToManyField(through='restapi.Employee_tech_skills', to='restapi.employees')),
            ],
        ),
        migrations.AddField(
            model_name='employee_tech_skills',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xx', to='restapi.employees'),
        ),
        migrations.AddField(
            model_name='employee_tech_skills',
            name='tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech', to='restapi.techs'),
        ),
    ]
