# Generated by Django 4.1.5 on 2023-03-13 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee_certificates',
            options={'ordering': ['cert_id']},
        ),
        migrations.AlterField(
            model_name='employee_certificates',
            name='cert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_id', to='restapi.certificate'),
        ),
    ]
