# Generated by Django 4.1.5 on 2023-03-13 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee_tech_skills',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='restapi.employees'),
        ),
        migrations.CreateModel(
            name='Employee_certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateField(null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='restapi.certificates')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certs', to='restapi.employees')),
            ],
            options={
                'ordering': ['certificate'],
            },
        ),
        migrations.AddField(
            model_name='certificates',
            name='employee',
            field=models.ManyToManyField(through='restapi.Employee_certificates', to='restapi.employees'),
        ),
    ]
