# Generated by Django 4.1.5 on 2023-02-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_users_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Employees',
        ),
        migrations.RenameField(
            model_name='employee_tech_skills',
            old_name='user',
            new_name='employee',
        ),
    ]
