# Generated by Django 4.1.5 on 2023-03-13 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_alter_employee_certificates_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_participation_start_date', models.DateField(null=True)),
                ('employee_participation_end_date', models.DateField(null=True)),
                ('allocation_busy', models.IntegerField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='restapi.employees')),
            ],
            options={
                'ordering': ['project'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(null=True)),
                ('project_start_date', models.DateField(null=True)),
                ('project_end_date', models.DateField(null=True)),
                ('confidential', models.BooleanField(null=True)),
                ('employee', models.ManyToManyField(through='restapi.Employee_projects', to='restapi.employees')),
            ],
        ),
        migrations.AddField(
            model_name='employee_projects',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_project', to='restapi.project'),
        ),
    ]
