# Generated by Django 4.1.5 on 2023-02-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_rename_users_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='allocation_until',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='location_city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='location_country',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='phone_number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='wants_not_to_do',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='wants_to_do',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='worktime_allocation',
            field=models.IntegerField(null=True),
        ),
    ]
