# Generated by Django 4.1.5 on 2023-03-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_employee_projects_project_employee_projects_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.TextField(default='null', unique=True),
            preserve_default=False,
        ),
    ]
