# Generated by Django 4.1.5 on 2023-02-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_employees_allocation_until_employees_location_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techs',
            name='employee',
            field=models.ManyToManyField(through='restapi.Employee_tech_skills', to='restapi.employees'),
        ),
    ]
