# Generated by Django 4.1.5 on 2023-02-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_techs_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='techs',
            name='tech_name',
            field=models.TextField(unique=True),
        ),
    ]
