# Generated by Django 4.1.5 on 2023-02-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_techs_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_tech_skills',
            name='tech_preference',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='techs',
            name='tech_name',
            field=models.TextField(unique=True),
        ),
    ]
