# Generated by Django 4.1.5 on 2023-04-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_token_is_integration_token_token_token_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='UmcpndsI1b2vSC08XN88gpG8VEvgVSjug5EZy985j6LFaRVzO4z2PBGIlaA1MlRi', max_length=64, unique=True),
        ),
    ]
