# Generated by Django 4.1.5 on 2023-04-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_token_is_integration_token_token_token_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='xs84s7bveZ3mEHj849RKaEPi68JXGJNOYq8Z8o7cqpSQiqgHshqeKCTuZT5Dj5nz', max_length=64, unique=True),
        ),
    ]
