# Generated by Django 4.1.5 on 2023-04-24 09:33

from django.db import migrations, models
import restapi.utils


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='is_integration_token',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default=restapi.utils.generate_token, max_length=64, unique=True),
        ),
    ]
