# Generated by Django 4.1.5 on 2023-04-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='is_integration_token',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='iR172ukWCmRdw1yatlpUBGYOV1Omv0asQS65HExH5BwtR3RNSHAvCl45P8wV2OTB', max_length=64, unique=True),
        ),
    ]
