# Generated by Django 4.1.5 on 2023-04-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_alter_token_is_integration_token_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='hNbZUoChwXaGzQLdBMgdBoUPuIgBsFieIrq927tEMrYbahUyvWTi2hh6yt9hIPe4', max_length=64),
        ),
    ]
