# Generated by Django 4.1.5 on 2023-04-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='pS5PA9hy37Wc14JVBi4RQ0TKgQI0xtYRq2jGDQWheKr49Qb0a17H5eD37hVxWebi', max_length=64, unique=True),
        ),
    ]
