# Generated by Django 4.1.5 on 2023-04-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='BBzPFhEDutM0teUdCkaXbmnvPLCGZpgR3xVJSQluYbo15CaELMa3P4ZEGa6E5faj', max_length=64, unique=True),
        ),
    ]
