name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Remove Roboroute
        run: sed -i '/Roboroute\|<*Routes>\|Routes,/d' frontend/src/Components/AuthRoutes.js

      - name: Remove File
        run: rm -rf frontend/src/Components/Roboroute.js

      - name: Create .env file
        run: |
          echo "${{ secrets.PRODUCTION_ENV_FILE }}" | base64 -d > .env

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          known_hosts: "allyourbasearebelongtous"

      - name: Add Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER }} >> ~/.ssh/known_hosts

      - name: Sync files with rsync
        run: rsync -avz . ${{ secrets.PRODUCTION_SSH_USER }}@${{ secrets.SERVER }}:${{ secrets.PRODUCTION_DEPLOY_PATH }}

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.PRODUCTION_SSH_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd production
            cp .env backend/
            cp .env frontend/
            docker compose -f docker-compose.production.yml up -d --build
