name: Test deployment

on:
  push:
    branches: 
      - skeleton
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Create .env file
        run: |
          python3 test.py $(echo ${{ secrets.ENV_FILE }})
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: 'plaa plaa'
          
      - name: Add Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
      - name: Sync files with rsync
        run: rsync -avz . ${{ secrets.DEPLOY_SSH_USER }}@${{ secrets.SSH_HOST }}:/home/deploytest/deploy/

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.DEPLOY_SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd deploy
            cp .env backend/
            docker compose up -d